export const disease = [
    { key: 'ds', name: 'Down syndrome (Trisomy 21)' },
    { key: 'fs', name: 'FragileX syndrome' },
    { key: 'ks', name: 'Klinefelter syndrome' },
    { key: 'txs', name: 'Triple-X syndrome' },
    { key: 'ts', name: 'Turner syndrome' },
    { key: 't18', name: 'Trisomy 18' },
    { key: 't13', name: 'Trisomy 13' },
    { key: 'cs', name: 'Cystic fibrosis' },
    { key: 'wq', name: 'Deafness that’s present at birth (congenital)' },
    { key: 'bgdf', name: 'Duchenne muscular dystrophy' },
    { key: 'sdc', name: 'Familial hypercholesterolemia,' },
    { key: 'ndnd', name: 'Hemochromatosis (iron overload)' },
    { key: 'lklk', name: 'Neurofibromatosis type 1 (NF1)' },
    { key: 'mjmj', name: 'Sickle cell disease' },
    { key: 'hnhn', name: 'Tay-Sachs disease' },
    { key: 'vgvg', name: 'Late-onset Alzheimer’s disease' },
    { key: 'yhyh', name: 'Arthritis' },
    { key: 'rgrg', name: 'Autism spectrum disorder, in most cases' },
    { key: 'uhuh', name: 'Cancer, in most cases' },
    { key: 'vfvf', name: 'Coronary artery disease' },
    { key: 'sdsd', name: 'Diabetes' },
    { key: 'sxsx', name: 'Migraine headaches' },
    { key: 'zxzx', name: 'Spina bifida' },
    { key: 'xzxz', name: 'Isolated congenital heart defects' },
];
